services:
  postgres:
    image: postgres:16
    container_name: issueflow_db
    environment:
      POSTGRES_USER: issueflow
      POSTGRES_PASSWORD: issueflow
      POSTGRES_DB: issueflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: